title:            "Ali Mannan Tirmizi"
owner:
  name: Ali Mannan Tirmizi
  avatar: /images/avatar.jpg
url:              0.0.0.0:4000
permalink:        pretty
highlighter:      pygments
markdown:         kramdown
google_analytics:
timezone:         Asia/Karachi
paginate: 5
gems:
  - jemoji
  - jekyll-mentions
